/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import config.ConfigReader;
import domain.User;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import server.Server;
import thread.ClientThread;

/**
 *
 * @author Ljubomir
 */
public class ServerUI extends javax.swing.JFrame {
    public ArrayList<User> users;
    public DefaultTableModel model;
    String maxBrojKorisnika;
    Server server;
    /**
     * Creates new form ServerUI
     */
    public ServerUI(Server server) {
        this.server = server;
        maxBrojKorisnika = new ConfigReader().getMaxCustomers();
        initComponents();
        users = new ArrayList<>();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        model = new DefaultTableModel();
        model.addColumn("FirstName");
        model.addColumn("LastName");
        jTable1.setModel(model);
        txtBrojKorisnika.setText(maxBrojKorisnika);
        txtBrojKorisnika.setEditable(false);
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBrojKorisnika = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnOdjavi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Online Korisnici :");

        jLabel2.setText("max broj korisnika:");

        btnOdjavi.setText("LogOut User");
        btnOdjavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjaviActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOdjavi)
                        .addGap(29, 29, 29))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBrojKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBrojKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnOdjavi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdjaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviActionPerformed
        LogOutUser();
    }//GEN-LAST:event_btnOdjaviActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjavi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBrojKorisnika;
    // End of variables declaration//GEN-END:variables

    public void updateTable() {
        // Clear existing rows
        model.setRowCount(0);

        // Add users to the table
        for (User user : users) {
            model.addRow(new Object[]{user.getFirstname(), user.getLastname()});
        }

        // Notify the table model that the data has changed
        model.fireTableDataChanged();
    }
    
    public void addUser(User user) {
        users.add(user);
        updateTable();
    }
    
     public void removeUser(User user) {
        users.remove(user);
        updateTable();
    }

    private void LogOutUser() {
        
        int selectedRow = jTable1.getSelectedRow();
        
        if(selectedRow != -1){
            User user = new User();
            user.setUsername((String) model.getValueAt(selectedRow, 1));
            System.out.println(user.getUsername());
            server.logOutUser(user);
            
        }
    }
  
}
